# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProfileList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Moya'

  # Pods for ProfileList

  target 'ProfileListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProfileListUITests' do
    # Pods for testing
  end

end
